spring:
  profiles:
    include:
      - fastapi
      - server
  application:
    name: positivetalk
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}}