spring:
  profiles:
    include: server
  application:
    name: apigateway
  cloud: # Reactive Gateway
    gateway:
      routes:
        - id: positivetalk
          predicates:
            - Path=/positivetalk/**
          uri: lb://positivetalk # Load Balancing
        - id: bottledupfeeling
          predicates:
            - Path=/bottledupfeeling/**
          uri: lb://bottledupfeeling
        - id: account
          predicates:
            - Path=/account/**
          uri: lb://account

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
